name: Build & Push Docker Images when main branch is updated

on:
  push:
    branches: ['main']

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      # ─── build & push API image ─────────────────────────────────────────
      - name: Build & Push NestJS image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.HARBOR_REGISTRY }}/test/api/${{ github.head_ref || github.ref_name}}:latest

      # ─── build & push Web image ─────────────────────────────────────────
      - name: Build & Push Next.js image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.HARBOR_REGISTRY }}/test/frontend/${{ github.head_ref || github.ref_name}}:latest

      - name: Deploying API
        uses: dkershner6/post-api-call-action@v2
        with:
          url: ${{ secrets.DEPLOY_API_URL }}
          data: '{\"sourceProjectName\": \"${{secrets.SOURCE_PROJECT_NAME}}\", \"serviceName\": \"api\", \"branchName\": \"${{ github.head_ref || github.ref_name }}\",\"sourceAppId\": \"${{ secrets.SOURCE_API_APP_ID }}\", \"projectId\": \"${{ secrets.PROJECT_ID }}\"}'
          # headers: "{\"Authorization\": \"Bearer ${{ secrets.API_KEY }}\"}"
      - name: Deploying Frontend
        uses: dkershner6/post-api-call-action@v2
        with:
          url: ${{ secrets.DEPLOY_API_URL }}
          data: '{\"sourceProjectName\": \"${{secrets.SOURCE_PROJECT_NAME}}\", \"serviceName\": \"frontend\", \"branchName\": \"${{ github.head_ref || github.ref_name }}\",\"sourceAppId\": \"${{ secrets.SOURCE_FRONTEND_APP_ID }}\", \"projectId\": \"${{ secrets.PROJECT_ID }}\"}'
          # headers: "{\"Authorization\": \"Bearer ${{ secrets.API_KEY }}\"}"
