name: Deploy preview on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build-preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    uses: ./.github/workflows/common-deploy.yml
    secrets: inherit
  deploy-preview:
    needs: build-preview
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    uses: ./.github/workflows/deploy-preview.yml
    secrets: inherit
